name: CommonAbilities
main: net.inkyquill.equestria.ca.CommonAbilities
version: 1.6.0c
commands:
  restrictTarget:
    description: restrict monster to target a player.
    aliases: restrictTarget
  eff:
    description: add/remove effects for player.
    aliases: effects
  death:
    description: manage death events.
  gms:
    description: reworked game master abilities.
  timemanager:
    description: manages world time settings.
    aliases: tm
  meteo:
    description: manage weather.
    aliases: wth